{if $type == 'Distribution'}

<table>
    <tr>
        <td style='width: 50%'>
            <table>
                <tr>
                    <td>{$nameName}</td>
                    <td>{$name}</td>
                </tr>
                <tr>
                    <td>{$installation_typeName}</td>
                    <td>{$installation_type}</td>
                </tr>
                <tr>
                    <td>{$installation_methodName}</td>
                    <td>{$installation_method}</td>
                </tr>
                <tr>
                    <td>{$originName}</td>
                    <td>{$origin}</td>
                </tr>
            </table>
        </td>
        <td>
            <table>
                <tr>
                    <td>{$architecturesName}</td>
                    <td>{$architectures}</td>
                </tr>
                <tr>
                    <td>{$componentsName}</td>
                    <td>{$components}</td>
                </tr>
                <tr>
                    <td>{$mirror_sourcesName}</td>
                    <td>{$mirror_sources}</td>
                </tr>
            </table>
        </td>
    </tr>
</table>
{else if $type == 'Release'}
<table>
    <tr>
        <td>{$nameName}</td>
        <td>{$name}</td>
    </tr>
</table>
{/if}
